### ISSUE TITLE
Wish: allow literal strings as path elements

### ISSUE THREAD

**Issue by meijeru** [rebol/rebol#19]
Currently, the following lexical and syntactical forms are allowed as path elements:
literal value except string, lit-word, word (which is not evaluated), get-word (evaluated, result may be of any type), and parenthesized expression (evaluated, result may again be of any type)

BrianH says: The " character is a delimiter, and apparently of higher precedence than paths (or is it lower?). This is the same as R2, but it would be useful to change because using strings as keys in blocks and maps is extremely common. 

This could be easy to implement without impact since the current behavior results in an error.

Reference: http://curecode.org/rebol3/ticket.rsp?id=746

**Comment by carls** [comment]
I would like to keep bug reports in curecode and save this github <b>issues area</b> for problems with builds, pulls, merges, branches, etc.

That said, it would be good to have a "priority" list somewhere for wish items like this one that make a lot of sense to implement sooner rather than later.

And finally, this wish item is fairly easy to add. The precedence of " is not relevant because the lexical analyzer has already split the char stream into values. It' just a matter of allowing strings within the path evaluator.

I will be closing all of these curecode bugs (that do not have code submitted) from this issues list.
