### ISSUE TITLE
Needing a version number for R3/Droid

### ISSUE THREAD

**Issue by ladislav** [rebol/rebol#68]
Hi, Carl, what do you think would be an appropriate platform number for Android? Cyphre seems to prefer 0.6.01 for android_arm.

**Comment by angerangel** [comment]
I agree

**Comment by BrianHawley** [comment]
That conflicts with the R2 numbering, where 6 was BSDi. We've avoided these kinds of conflicts before - are we going to continue to do so? I'm not sure it's that big a deal, since code that requires platform-detection unlikely to be portable between R2 and R3 anyway. Also, does anyone plan to support BSDi in R3?

The next available major number is 13. We can decide for ourselves whether that number being considered unlucky in most western cultures should be a factor; it's lucky in China at least.

We should consider having separate platform numbers for command line programs that happen to run on Android in the unlikely event of having a command line installed there (basically Linux programs), and for a proper Android port. A real Android programming language has more in common with a Java extension than a Linux app. The core might be compiled by the same compiler, but the host API would be completely different.

**Comment by angerangel** [comment]
13 is good to me, I'm not a scaramantic person.  _(In every country 13 and 17 number meaning is different, for somebody is luck,for somebody else is unluck)_

**Comment by hostilefork** [comment]
While I thought the 0.5.75 for HaikuOS was funny, it seems worth questioning what flattening platforms into numbers is buying...

Numbers make sense when you need to do greater-than or less-than comparisons.  It seems there is a "platform/architecture" choice at work, e.g. `osx/ppc` or `osx/x86` or `osx/x64`.  Should these be PATH! instead?

And if Rebol is going to use numbers for versions, I'm going to board the boat that asks for R3 to start numbering itself 3.y.z.  In light of the recent blog post I understand the reluctance to say _"it's not a 3 point oh yet"_, but the Internet age has killed the release-to-manufacturing concept.  Better to know what the major version _is_.

I'd prefer the KDE versioning system.  Their X.Y.Z is such that X is the major architecture difference (a new Qt version in their case), Y is bumped when interface changes produce incompatibilities, and Z is bumped for maintenance and bugfixes.

**Comment by BrianHawley** [comment]
We'll go to 3.0.x.x.x when we get to at least beta stage (or release stable, not my call). We have a lot of work to do to get to that point.

**Comment by earl** [comment]
I'd prefer to get rid of the platform numbering as well, and switch to feature flags (the already existent `system/platform` is a first step towards that). The sooner this move happens, the better. However, until we get there, 6.1 seems ok to (re-)use.

**Comment by BrianHawley** [comment]
You can't use `and` or other bitwise operations on paths the way you can on tuples, and paths are structures while tuples are immediate values so paths are slower to compare. That's a trade-off to consider.

We might consider keeping the numeric platform.architecture (since it adds no overhead to version numbers), but also have a path platform/architecture available. Or maybe a block [platform architecture], since that's structurally the same as a path. We can even make it available in `system/platform` where you can check it at runtime. Oh wait, look, it's already there.

**Comment by hostilefork** [comment]
In the world of micro-optimizations, I hardly think the performance of PATH! here is going to be a bottleneck.  :-)

It would be nice if the same structure used as a parameter to the make process was human readable, and could even be used on the [build page](http://rebolsource.net/) _as the actual name of the build_.  That removes the need for mapping from a "pretty name".  **Linux/x64** is as good or better than **Linux x64**.

_I guess a block would be fine too, though it would suck to have to carry the brackets as in `[Linux x64]`.  Not the end of the world either way.  The point is: human readable, structural, lose the arbitrary numbers, no mapping._

**Comment by earl** [comment]
For feature testing, tuple! and path! are equally bad. To better solution is feature flags: think `r3?`, `linux?`, `32-bit?`, `core?`, `view?`, etc (but with a slightly different implementation).

For description, human-readable indeed is the primary criterion. I'd prefer e.g. `linux-x86` over `linux/x86` (because I don't want to imply a hierarchy and by not doing so retain flexibility), but that's then only a matter of taste. 

With those two parts in place, we can get rid of the arbitrary numbers.

**Comment by BrianHawley** [comment]
I would rather have both `Linux` and `linux-x86` in `system/platform` because there will be the need to test for Linux API stuff that will exist on the platform regardless of what the hardware platform is (for stuff you access through `call`, for instance), and on other occasions for stuff that would be more hardware-specific. As for the flags you suggest, Andreas, as long as they're not functions exported to words in `lib` directly, that would be nice. If they are functions then they don't have to be loaded by default, they can be in a delay-loaded utility module.
