### ISSUE TITLE
Arithmetic bug with decimal

### ISSUE THREAD

**Issue by trembmax** [rebol/rebol#79]
A bug which appears on Rebol2 and r3-a111-3-1 at least on Windows and Linux:
Some simple arithmetic leads to incorrect results with decimal type.
Here is a simple example:

```
>> -8.45 + 8.0 + 0.45
== 7.21644966006352e-16
```

Should instead be 0.

**Comment by hostilefork** [comment]
Hi @trembmax ...

Rebol does not manipulate numbers by digits symbolically like a human would on paper.  Most languages don't--in fact--because it's a slow way to do math on a machine.  On StackOverflow, this is the website that people are often pointed to who have this question

[What Every Programmer Should Know About Floating-Point Arithmetic](http://floating-point-gui.de/)

...although bear in mind that Rebol's `decimal!` datatype is actually a just a floating point number (not a "decimal" in the sense they speak of).  For precise currency calculations Rebol has `money!`

Speaking of StackOverflow, feel free to join us in the [Rebol and Red chat room](http://chat.stackoverflow.com/rooms/291/rebol-and-red) there...

**Comment by trembmax** [comment]
Hi @hostilefork,
Sorry but I have to disagree on two points.

First, the rebol data type is called decimal!. It should behave like a decimal number. Not like a floating point.

> > type? -8.45
> > == decimal!
> > type? 8.0
> > == decimal!
> > type? 0.45
> > == decimal!
> > type? -8.45 + 8.0 - 0.45
> > == decimal!

It is somehow philosophical, but if rebol want it to behave like a float, it should call it a float. 
This way programmers won't assume it will behave like a decimal number and will take the appropriate steps to explicitly round up the results according to their needs. 

On the same reference you pointed out, there is something about decimals:
http://floating-point-gui.de/formats/exact/

Second, the money! type just hide the problem on the display. The underling calculations are still wrong:

> > a: -$8.45 + $8.0 + $0.45
> > == $0.00
> > while [true] [
> >     a: a + a 
> >     if a > $1.0 [
> >         probe a break
> >     ]
> > ]
> > $1.63
> > This is clearly a wrong result.

In fact we can see that the "internal" representation of the money! is a decimal! :

> > a: -$8.45 + $8.0 + $0.45
> > == $0.00
> > probe second a
> > 7.21644966006352E-16

Best Regards

**Comment by rebolek** [comment]
Trembmax, unlike in R2, which you clearly used, in R3 is money! datatype
BCD internally.

**Comment by trembmax** [comment]
rebolek, you are right about money! in r3, my mistake. I tried it with more than two decimal digits and it still is working, so r3 already solved the problem I raised.

First point still holds though, and I personally think that "money"  should really be named "decimal"  but it is truly philosophical, so it is not an issue needing to be solved.

Thanks
